let products = [
  {
    name: "MacBook Pro",
    category: "Laptops",
    price: 1299,
    description: "Powerful Apple laptop with M1 chip",
    inStock: true,
    image: "https://example.com/macbook-pro.jpg",
  },
  {
    name: "Dell XPS",
    category: "Laptops",
    price: 999,
    description: "High-end Windows laptop with InfinityEdge display",
    inStock: true,
    image: "https://example.com/dell-xps.jpg",
  },
  {
    name: "HP Spectre",
    category: "Laptops",
    price: 1100,
    description: "Sleek design and great performance",
    inStock: false,
    image: "https://example.com/hp-spectre.jpg",
  },
  {
    name: "Asus ZenBook",
    category: "Laptops",
    price: 850,
    description: "Affordable ultrabook with solid specs",
    inStock: true,
    image: "https://example.com/asus-zenbook.jpg",
  },
  {
    name: "Lenovo ThinkPad",
    category: "Laptops",
    price: 950,
    description: "Business-grade laptop with excellent keyboard",
    inStock: true,
    image: "https://example.com/lenovo-thinkpad.jpg",
  },
  {
    name: "RGB Mousepad",
    category: "Gaming Accessories",
    price: 35,
    description: "Large RGB mousepad with smooth surface",
    inStock: true,
    image: "https://example.com/rgb-mousepad.jpg",
  },
  {
    name: "Gaming Chair",
    category: "Gaming Accessories",
    price: 150,
    description: "Comfortable ergonomic chair for gamers",
    inStock: false,
    image: "https://example.com/gaming-chair.jpg",
  },
  {
    name: "Mechanical Keyboard",
    category: "Gaming Accessories",
    price: 120,
    description: "Mechanical keys with customizable RGB",
    inStock: true,
    image: "https://example.com/mechanical-keyboard.jpg",
  },
  {
    name: "Gaming Mouse",
    category: "Gaming Accessories",
    price: 80,
    description: "High precision wireless gaming mouse",
    inStock: true,
    image: "https://example.com/gaming-mouse.jpg",
  },
  {
    name: "VR Headset",
    category: "Gaming Accessories",
    price: 400,
    description: "Immersive VR experience with wide FOV",
    inStock: true,
    image: "https://example.com/vr-headset.jpg",
  },
  // ... add similarly until id: 100
];
